[2023-11-16T20:15:51.008+0000] {processor.py:153} INFO - Started process (PID=12122) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:15:51.008+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:15:51.009+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:15:51.009+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:15:51.011+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:15:51.010+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2023-11-16T20:15:51.011+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:15:51.052+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.046 seconds
[2023-11-16T20:15:53.149+0000] {processor.py:153} INFO - Started process (PID=12132) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:15:53.149+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:15:53.150+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:15:53.150+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:15:53.152+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:15:53.151+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 3
    from airflow.operators
                          ^
SyntaxError: invalid syntax
[2023-11-16T20:15:53.152+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:15:53.188+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.041 seconds
[2023-11-16T20:16:13.484+0000] {processor.py:153} INFO - Started process (PID=12270) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:13.485+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:16:13.485+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:13.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:13.490+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:13.524+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2023-11-16T20:16:16.675+0000] {processor.py:153} INFO - Started process (PID=12296) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:16.676+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:16:16.677+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:16.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:16.681+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:16.688+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.014 seconds
[2023-11-16T20:16:20.072+0000] {processor.py:153} INFO - Started process (PID=12318) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:20.072+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:16:20.073+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:20.073+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:20.077+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:20.083+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.013 seconds
[2023-11-16T20:16:28.692+0000] {processor.py:153} INFO - Started process (PID=12380) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:28.692+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:16:28.693+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:28.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:28.695+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:28.694+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 8
    'depen'
          ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:16:28.695+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:28.732+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2023-11-16T20:16:32.684+0000] {processor.py:153} INFO - Started process (PID=12399) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:32.685+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:16:32.686+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:32.685+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:32.688+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:32.687+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 8
    'depends_on_past'
                    ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:16:32.688+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:32.727+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.044 seconds
[2023-11-16T20:16:47.122+0000] {processor.py:153} INFO - Started process (PID=12499) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:47.123+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:16:47.123+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:47.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:47.125+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:47.124+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 9
    'email_on_failure'
                     ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:16:47.125+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:47.163+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.043 seconds
[2023-11-16T20:16:58.138+0000] {processor.py:153} INFO - Started process (PID=12567) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:58.138+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:16:58.139+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:58.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:58.141+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:16:58.140+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 10
    'email_on_retry'
                   ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:16:58.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:16:58.177+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.041 seconds
[2023-11-16T20:17:03.307+0000] {processor.py:153} INFO - Started process (PID=12596) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:03.308+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:03.308+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:03.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:03.310+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:03.310+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 11
    ''
     ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:17:03.311+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:03.350+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:17:05.505+0000] {processor.py:153} INFO - Started process (PID=12612) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:05.506+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:05.506+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:05.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:05.508+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:05.507+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 11
    'retries'
            ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:17:05.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:05.548+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:17:14.604+0000] {processor.py:153} INFO - Started process (PID=12673) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:14.605+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:14.605+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:14.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:14.607+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:14.606+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 12
    'catchup'
            ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:17:14.607+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:14.642+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.040 seconds
[2023-11-16T20:17:16.806+0000] {processor.py:153} INFO - Started process (PID=12686) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:16.808+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:16.808+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:16.808+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:16.813+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:16.812+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 12
    'catchup': 
             ^
SyntaxError: expression expected after dictionary key and ':'
[2023-11-16T20:17:16.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:16.853+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.051 seconds
[2023-11-16T20:17:18.640+0000] {processor.py:153} INFO - Started process (PID=12705) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:18.642+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:18.643+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:18.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:18.645+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:18.644+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 13
    s
    ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:17:18.650+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:18.690+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.059 seconds
[2023-11-16T20:17:22.332+0000] {processor.py:153} INFO - Started process (PID=12731) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:22.332+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:22.333+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:22.333+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:22.335+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:22.334+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 13
    'start_date'
               ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:17:22.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:22.377+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.047 seconds
[2023-11-16T20:17:24.859+0000] {processor.py:153} INFO - Started process (PID=12751) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:24.860+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:24.860+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:24.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:24.863+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:24.862+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 13
    'start_date'_
               ^
SyntaxError: ':' expected after dictionary key
[2023-11-16T20:17:24.864+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:24.906+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.050 seconds
[2023-11-16T20:17:30.319+0000] {processor.py:153} INFO - Started process (PID=12802) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:30.320+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:30.321+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:30.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:30.327+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:30.326+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 13, in <module>
    'start_date': datetime(2023,1)
TypeError: function missing required argument 'day' (pos 3)
[2023-11-16T20:17:30.327+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:30.362+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:17:37.026+0000] {processor.py:153} INFO - Started process (PID=12831) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:37.027+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:37.028+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:37.027+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:37.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:37.068+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.044 seconds
[2023-11-16T20:17:38.968+0000] {processor.py:153} INFO - Started process (PID=12856) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:38.969+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:38.969+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:38.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:38.975+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:38.980+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.014 seconds
[2023-11-16T20:17:43.314+0000] {processor.py:153} INFO - Started process (PID=12878) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:43.315+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:43.315+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:43.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:43.322+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:43.320+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16, in <module>
    with_
NameError: name 'with_' is not defined
[2023-11-16T20:17:43.323+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:43.358+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:17:44.140+0000] {processor.py:153} INFO - Started process (PID=12879) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:44.140+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:44.141+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:44.141+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:44.147+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:44.146+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16, in <module>
    wit
NameError: name 'wit' is not defined
[2023-11-16T20:17:44.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:44.193+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.056 seconds
[2023-11-16T20:17:47.378+0000] {processor.py:153} INFO - Started process (PID=12901) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:47.378+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:47.379+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:47.379+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:47.380+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:47.380+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG{}
            ^
SyntaxError: invalid syntax
[2023-11-16T20:17:47.381+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:47.419+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.044 seconds
[2023-11-16T20:17:49.306+0000] {processor.py:153} INFO - Started process (PID=12927) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:49.306+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:49.307+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:49.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:49.309+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:49.308+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG{
            ^
SyntaxError: invalid syntax
[2023-11-16T20:17:49.309+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:49.344+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.040 seconds
[2023-11-16T20:17:52.547+0000] {processor.py:153} INFO - Started process (PID=12943) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:52.548+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:52.549+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:52.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:52.550+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:52.550+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG{
            ^
SyntaxError: invalid syntax
[2023-11-16T20:17:52.551+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:52.587+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2023-11-16T20:17:58.349+0000] {processor.py:153} INFO - Started process (PID=12990) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:58.350+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:17:58.351+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:58.351+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:58.354+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:17:58.353+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 17
    dag_id='one_task_dag'
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2023-11-16T20:17:58.354+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:17:58.401+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.055 seconds
[2023-11-16T20:18:02.655+0000] {processor.py:153} INFO - Started process (PID=13012) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:02.655+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:02.656+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:02.656+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:02.658+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:02.657+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 17
    dag_id='one_task_dag',
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2023-11-16T20:18:02.658+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:02.694+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2023-11-16T20:18:13.373+0000] {processor.py:153} INFO - Started process (PID=13081) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:13.374+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:13.374+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:13.374+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:13.376+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:13.375+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 17
    dag_id='one_task_dag',
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2023-11-16T20:18:13.376+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:13.416+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.046 seconds
[2023-11-16T20:18:20.856+0000] {processor.py:153} INFO - Started process (PID=13136) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:20.857+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:20.857+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:20.857+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:20.859+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:20.858+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 17
    dag_id='one_task_dag',
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2023-11-16T20:18:20.859+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:20.893+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2023-11-16T20:18:25.364+0000] {processor.py:153} INFO - Started process (PID=13158) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:25.365+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:25.365+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:25.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:25.367+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:25.366+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 17
    dag_id='one_task_dag',
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2023-11-16T20:18:25.367+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:25.407+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.047 seconds
[2023-11-16T20:18:26.515+0000] {processor.py:153} INFO - Started process (PID=13165) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:26.515+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:26.516+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:26.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:26.518+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:26.517+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 17
    dag_id='one_task_dag',
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2023-11-16T20:18:26.518+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:26.551+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2023-11-16T20:18:32.004+0000] {processor.py:153} INFO - Started process (PID=13210) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:32.005+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:32.005+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:32.005+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:32.008+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:32.007+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG)
            ^
SyntaxError: unmatched ')'
[2023-11-16T20:18:32.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:32.051+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.051 seconds
[2023-11-16T20:18:34.204+0000] {processor.py:153} INFO - Started process (PID=13223) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:34.205+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:34.205+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:34.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:34.207+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:34.206+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG)
            ^
SyntaxError: unmatched ')'
[2023-11-16T20:18:34.208+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:34.241+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2023-11-16T20:18:36.032+0000] {processor.py:153} INFO - Started process (PID=13233) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:36.032+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:36.033+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:36.033+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:36.035+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:36.034+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG)
            ^
SyntaxError: unmatched ')'
[2023-11-16T20:18:36.035+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:36.070+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.040 seconds
[2023-11-16T20:18:38.221+0000] {processor.py:153} INFO - Started process (PID=13240) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:38.222+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:38.222+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:38.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:38.224+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:38.223+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG)
            ^
SyntaxError: unmatched ')'
[2023-11-16T20:18:38.224+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:38.267+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.048 seconds
[2023-11-16T20:18:40.032+0000] {processor.py:153} INFO - Started process (PID=13271) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:40.033+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:40.034+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:40.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:40.036+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:40.035+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG)
            ^
SyntaxError: unmatched ')'
[2023-11-16T20:18:40.036+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:40.069+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.040 seconds
[2023-11-16T20:18:42.231+0000] {processor.py:153} INFO - Started process (PID=13281) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:42.232+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:42.232+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:42.232+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:42.235+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:42.234+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG)
            ^
SyntaxError: unmatched ')'
[2023-11-16T20:18:42.235+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:42.272+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.044 seconds
[2023-11-16T20:18:45.198+0000] {processor.py:153} INFO - Started process (PID=13294) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:45.199+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:45.200+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:45.199+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:45.202+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:45.201+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG)
            ^
SyntaxError: unmatched ')'
[2023-11-16T20:18:45.202+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:45.244+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.048 seconds
[2023-11-16T20:18:47.426+0000] {processor.py:153} INFO - Started process (PID=13310) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:47.427+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:18:47.427+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:47.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:47.430+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:18:47.429+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 16
    with DAG)
            ^
SyntaxError: unmatched ')'
[2023-11-16T20:18:47.430+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:18:47.465+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.041 seconds
[2023-11-16T20:19:03.738+0000] {processor.py:153} INFO - Started process (PID=13419) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:03.739+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:03.740+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:03.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:03.759+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:03.757+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1
NameError: name 'task1' is not defined
[2023-11-16T20:19:03.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:03.803+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.068 seconds
[2023-11-16T20:19:06.764+0000] {processor.py:153} INFO - Started process (PID=13441) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:06.772+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:06.775+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:06.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:06.789+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:06.786+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1
NameError: name 'task1' is not defined
[2023-11-16T20:19:06.791+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:06.829+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.072 seconds
[2023-11-16T20:19:12.509+0000] {processor.py:153} INFO - Started process (PID=13481) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:12.511+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:12.512+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:12.512+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:12.552+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:12.542+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator()
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 377, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-11-16T20:19:12.553+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:12.633+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.139 seconds
[2023-11-16T20:19:15.759+0000] {processor.py:153} INFO - Started process (PID=13500) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:15.759+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:15.760+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:15.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:15.762+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:15.761+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    )
    ^
SyntaxError: invalid syntax
[2023-11-16T20:19:15.762+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:15.799+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2023-11-16T20:19:19.841+0000] {processor.py:153} INFO - Started process (PID=13516) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:19.844+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:19.845+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:19.845+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:19.866+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:19.861+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 377, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-11-16T20:19:19.867+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:19.935+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.099 seconds
[2023-11-16T20:19:22.024+0000] {processor.py:153} INFO - Started process (PID=13550) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:22.024+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:22.025+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:22.025+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:22.027+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:22.027+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    )
    ^
SyntaxError: invalid syntax
[2023-11-16T20:19:22.028+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:22.084+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.063 seconds
[2023-11-16T20:19:27.084+0000] {processor.py:153} INFO - Started process (PID=13572) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:27.085+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:27.086+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:27.085+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:27.092+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:27.091+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:19:27.093+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:27.128+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.047 seconds
[2023-11-16T20:19:35.290+0000] {processor.py:153} INFO - Started process (PID=13625) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:35.291+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:35.291+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:35.291+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:35.298+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:35.297+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:19:35.298+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:35.334+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.046 seconds
[2023-11-16T20:19:40.149+0000] {processor.py:153} INFO - Started process (PID=13653) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:40.149+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:40.150+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:40.150+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:40.151+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:40.151+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning"
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:19:40.152+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:40.188+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2023-11-16T20:19:42.290+0000] {processor.py:153} INFO - Started process (PID=13688) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:42.291+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:42.292+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:42.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:42.293+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:42.293+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" 
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:19:42.294+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:42.329+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2023-11-16T20:19:43.787+0000] {processor.py:153} INFO - Started process (PID=13689) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:43.788+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:43.789+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:43.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:43.790+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:43.790+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > 
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:19:43.791+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:43.824+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2023-11-16T20:19:47.353+0000] {processor.py:153} INFO - Started process (PID=13712) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:47.354+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:47.354+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:47.354+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:47.356+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:47.356+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > /works
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:19:47.357+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:47.396+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:19:51.327+0000] {processor.py:153} INFO - Started process (PID=13744) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:51.328+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:19:51.328+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:51.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:51.330+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:19:51.329+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > /workspace/hand
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:19:51.330+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:19:51.366+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.041 seconds
[2023-11-16T20:20:21.831+0000] {processor.py:153} INFO - Started process (PID=13929) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:20:21.832+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:20:21.833+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:20:21.833+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:20:21.835+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:20:21.835+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > /workspace/hand
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:20:21.836+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:20:21.868+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2023-11-16T20:20:52.403+0000] {processor.py:153} INFO - Started process (PID=14099) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:20:52.404+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:20:52.405+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:20:52.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:20:52.407+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:20:52.406+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > /workspace/hand
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:20:52.407+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:20:52.445+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:21:22.605+0000] {processor.py:153} INFO - Started process (PID=14269) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:21:22.606+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:21:22.606+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:21:22.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:21:22.608+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:21:22.607+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > /workspace/hand
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:21:22.608+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:21:22.642+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.040 seconds
[2023-11-16T20:21:53.383+0000] {processor.py:153} INFO - Started process (PID=14470) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:21:53.384+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:21:53.385+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:21:53.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:21:53.386+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:21:53.386+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > /workspace/hand
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:21:53.387+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:21:53.425+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:22:13.160+0000] {processor.py:153} INFO - Started process (PID=14589) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:13.160+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:22:13.161+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:13.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:13.163+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:13.162+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > /workspaces/hands-on-introduction-data-engineering-4395021/lab/temp
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:22:13.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:13.200+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2023-11-16T20:22:30.771+0000] {processor.py:153} INFO - Started process (PID=14716) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:30.772+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:22:30.773+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:30.773+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:30.776+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:30.776+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > /workspaces/hands-on-introduction-data-engineering-4395021/lab/temp/create-this-filñe
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:22:30.777+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:30.814+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:22:35.129+0000] {processor.py:153} INFO - Started process (PID=14756) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:35.130+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:22:35.131+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:35.130+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:35.133+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:35.132+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 25
    bash_command='echo "Hello, Linkedin learning" > /workspaces/hands-on-introduction-data-engineering-4395021/lab/temp/create-this-file.txt
                 ^
SyntaxError: unterminated string literal (detected at line 25)
[2023-11-16T20:22:35.133+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:35.177+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.050 seconds
[2023-11-16T20:22:40.195+0000] {processor.py:153} INFO - Started process (PID=14778) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:40.195+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:22:40.196+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:40.196+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:40.204+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:40.203+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:22:40.205+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:40.240+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.047 seconds
[2023-11-16T20:22:41.962+0000] {processor.py:153} INFO - Started process (PID=14788) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:41.962+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:22:41.963+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:41.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:41.970+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:41.969+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:22:41.970+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:42.009+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.050 seconds
[2023-11-16T20:22:45.284+0000] {processor.py:153} INFO - Started process (PID=14819) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:45.285+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:22:45.286+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:45.286+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:45.296+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:45.294+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:22:45.296+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:45.336+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.054 seconds
[2023-11-16T20:22:50.320+0000] {processor.py:153} INFO - Started process (PID=14842) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:50.321+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:22:50.322+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:50.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:50.335+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:22:50.334+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:22:50.336+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:22:50.369+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.052 seconds
[2023-11-16T20:23:20.741+0000] {processor.py:153} INFO - Started process (PID=15030) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:23:20.742+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:23:20.742+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:23:20.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:23:20.749+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:23:20.747+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:23:20.749+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:23:20.784+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.046 seconds
[2023-11-16T20:23:51.148+0000] {processor.py:153} INFO - Started process (PID=15209) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:23:51.149+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:23:51.149+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:23:51.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:23:51.156+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:23:51.155+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:23:51.156+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:23:51.191+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.044 seconds
[2023-11-16T20:24:21.327+0000] {processor.py:153} INFO - Started process (PID=15391) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:24:21.328+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:24:21.328+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:24:21.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:24:21.335+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:24:21.334+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:24:21.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:24:21.370+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:24:51.522+0000] {processor.py:153} INFO - Started process (PID=15577) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:24:51.523+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:24:51.523+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:24:51.523+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:24:51.530+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:24:51.529+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:24:51.530+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:24:51.565+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:25:21.738+0000] {processor.py:153} INFO - Started process (PID=15747) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:25:21.739+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:25:21.740+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:25:21.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:25:21.749+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:25:21.748+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:25:21.750+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:25:21.792+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.059 seconds
[2023-11-16T20:25:51.938+0000] {processor.py:153} INFO - Started process (PID=15932) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:25:51.939+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:25:51.940+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:25:51.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:25:51.946+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:25:51.945+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:25:51.946+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:25:51.981+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2023-11-16T20:26:22.112+0000] {processor.py:153} INFO - Started process (PID=16111) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:26:22.113+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:26:22.114+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:26:22.114+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:26:22.122+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:26:22.121+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:26:22.123+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:26:22.162+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.052 seconds
[2023-11-16T20:26:52.332+0000] {processor.py:153} INFO - Started process (PID=16299) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:26:52.333+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:26:52.333+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:26:52.333+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:26:52.340+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:26:52.339+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:26:52.340+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:26:52.373+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.044 seconds
[2023-11-16T20:27:22.525+0000] {processor.py:153} INFO - Started process (PID=16591) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:27:22.526+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:27:22.526+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:27:22.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:27:22.534+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:27:22.533+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:27:22.534+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:27:22.570+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.047 seconds
[2023-11-16T20:27:52.712+0000] {processor.py:153} INFO - Started process (PID=16789) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:27:52.713+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:27:52.713+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:27:52.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:27:52.720+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:27:52.719+0000] {dagbag.py:343} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23, in <module>
    task1 = BashOperator(
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'one task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-16T20:27:52.720+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:27:52.760+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.050 seconds
[2023-11-16T20:28:08.675+0000] {processor.py:153} INFO - Started process (PID=16877) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:08.676+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:28:08.677+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:08.676+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:08.689+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:08.820+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:08.820+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:one_task_dag
[2023-11-16T20:28:08.856+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:08.856+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:one_task_dag
[2023-11-16T20:28:08.899+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:08.899+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:one_task_dag
[2023-11-16T20:28:08.900+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:08.900+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:28:08.908+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:08.908+0000] {dag.py:2711} INFO - Creating ORM DAG for one_task_dag
[2023-11-16T20:28:08.915+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:08.915+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:28:09.058+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.385 seconds
[2023-11-16T20:28:10.201+0000] {processor.py:153} INFO - Started process (PID=16889) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:10.201+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:28:10.202+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:10.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:10.223+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:10.230+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:10.230+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:28:10.272+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:10.272+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:28:10.323+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.127 seconds
[2023-11-16T20:28:11.431+0000] {processor.py:153} INFO - Started process (PID=16895) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:11.432+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:28:11.432+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:11.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:11.444+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:11.450+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:11.449+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:28:11.466+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:11.466+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:28:11.505+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.077 seconds
[2023-11-16T20:28:41.611+0000] {processor.py:153} INFO - Started process (PID=17154) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:41.611+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:28:41.612+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:41.612+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:41.624+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:28:41.637+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:41.637+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:28:41.652+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:28:41.651+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:28:41.695+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.087 seconds
[2023-11-16T20:29:12.741+0000] {processor.py:153} INFO - Started process (PID=17335) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:29:12.742+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:29:12.743+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:29:12.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:29:12.754+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:29:12.767+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:29:12.767+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:29:12.784+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:29:12.784+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:29:12.825+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.087 seconds
[2023-11-16T20:29:43.134+0000] {processor.py:153} INFO - Started process (PID=17541) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:29:43.135+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:29:43.136+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:29:43.136+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:29:43.147+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:29:43.161+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:29:43.161+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:29:43.177+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:29:43.176+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:29:43.215+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.083 seconds
[2023-11-16T20:30:13.548+0000] {processor.py:153} INFO - Started process (PID=17878) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:30:13.548+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:30:13.549+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:30:13.549+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:30:13.561+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:30:13.574+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:30:13.574+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:30:13.590+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:30:13.589+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:30:13.627+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.081 seconds
[2023-11-16T20:30:44.018+0000] {processor.py:153} INFO - Started process (PID=18062) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:30:44.019+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:30:44.019+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:30:44.019+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:30:44.031+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:30:44.044+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:30:44.044+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:30:44.059+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:30:44.059+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:30:44.107+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.091 seconds
[2023-11-16T20:31:14.435+0000] {processor.py:153} INFO - Started process (PID=18244) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:31:14.436+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:31:14.436+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:31:14.436+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:31:14.448+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:31:14.461+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:31:14.461+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:31:14.476+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:31:14.476+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:31:14.514+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.081 seconds
[2023-11-16T20:31:37.059+0000] {processor.py:153} INFO - Started process (PID=18375) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:31:37.060+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:31:37.060+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:31:37.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:31:37.076+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:31:37.097+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:31:37.097+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:31:37.120+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:31:37.120+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:31:37.166+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.109 seconds
[2023-11-16T20:32:08.078+0000] {processor.py:153} INFO - Started process (PID=18563) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:32:08.080+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:32:08.080+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:32:08.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:32:08.093+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:32:08.107+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:32:08.107+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:32:08.121+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:32:08.121+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:32:08.157+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.081 seconds
[2023-11-16T20:32:38.265+0000] {processor.py:153} INFO - Started process (PID=18751) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:32:38.266+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:32:38.267+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:32:38.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:32:38.279+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:32:38.294+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:32:38.294+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:32:38.309+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:32:38.309+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:32:38.348+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.085 seconds
[2023-11-16T20:32:56.265+0000] {processor.py:153} INFO - Started process (PID=18891) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:32:56.266+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:32:56.267+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:32:56.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:32:56.267+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:32:56.267+0000] {dagbag.py:320} INFO - File /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py assumed to contain no DAGs. Skipping.
[2023-11-16T20:32:56.268+0000] {processor.py:755} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:32:56.277+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.016 seconds
[2023-11-16T20:35:28.941+0000] {processor.py:153} INFO - Started process (PID=19977) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:35:28.942+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:35:28.942+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:35:28.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:35:28.955+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:35:28.991+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:35:28.990+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:35:29.008+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:35:29.007+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:35:29.050+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.111 seconds
[2023-11-16T20:36:00.067+0000] {processor.py:153} INFO - Started process (PID=20177) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:36:00.067+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:36:00.068+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:36:00.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:36:00.079+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:36:00.093+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:36:00.092+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:36:00.107+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:36:00.107+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:36:00.149+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.084 seconds
[2023-11-16T20:36:30.375+0000] {processor.py:153} INFO - Started process (PID=20360) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:36:30.375+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:36:30.376+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:36:30.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:36:30.387+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:36:30.400+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:36:30.400+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:36:30.415+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:36:30.415+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:36:30.451+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.079 seconds
[2023-11-16T20:37:00.542+0000] {processor.py:153} INFO - Started process (PID=21192) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:37:00.543+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:37:00.544+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:37:00.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:37:00.556+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:37:00.570+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:37:00.570+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:37:00.585+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:37:00.585+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:37:00.647+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.107 seconds
[2023-11-16T20:37:31.321+0000] {processor.py:153} INFO - Started process (PID=21387) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:37:31.322+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:37:31.322+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:37:31.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:37:31.335+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:37:31.352+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:37:31.352+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:37:31.371+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:37:31.371+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:37:31.419+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.101 seconds
[2023-11-16T20:38:01.581+0000] {processor.py:153} INFO - Started process (PID=21566) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:38:01.582+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:38:01.583+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:38:01.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:38:01.594+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:38:01.608+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:38:01.608+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:38:01.623+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:38:01.623+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:38:01.661+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.082 seconds
[2023-11-16T20:38:31.761+0000] {processor.py:153} INFO - Started process (PID=22512) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:38:31.762+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:38:31.763+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:38:31.763+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:38:31.781+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:38:31.811+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:38:31.811+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:38:31.834+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:38:31.834+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:38:31.900+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.143 seconds
[2023-11-16T20:39:02.021+0000] {processor.py:153} INFO - Started process (PID=23146) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:39:02.022+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:39:02.023+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:39:02.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:39:02.039+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:39:02.057+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:39:02.057+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:39:02.081+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:39:02.081+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:39:02.122+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.103 seconds
[2023-11-16T20:39:32.371+0000] {processor.py:153} INFO - Started process (PID=23304) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:39:32.372+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:39:32.373+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:39:32.373+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:39:32.384+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:39:32.397+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:39:32.397+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:39:32.412+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:39:32.412+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:39:32.451+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.082 seconds
[2023-11-16T20:40:02.586+0000] {processor.py:153} INFO - Started process (PID=24455) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:40:02.616+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:40:02.617+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:40:02.617+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:40:02.703+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:40:02.788+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:40:02.788+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:40:02.862+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:40:02.862+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:40:02.958+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.375 seconds
[2023-11-16T20:40:33.159+0000] {processor.py:153} INFO - Started process (PID=24635) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:40:33.160+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:40:33.161+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:40:33.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:40:33.176+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:40:33.192+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:40:33.191+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:40:33.207+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:40:33.207+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:40:33.246+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.090 seconds
[2023-11-16T20:41:03.322+0000] {processor.py:153} INFO - Started process (PID=24805) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:41:03.323+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:41:03.324+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:41:03.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:41:03.342+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:41:03.362+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:41:03.362+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:41:03.391+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:41:03.391+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:41:03.437+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.119 seconds
[2023-11-16T20:41:33.590+0000] {processor.py:153} INFO - Started process (PID=24984) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:41:33.592+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:41:33.596+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:41:33.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:41:33.621+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:41:33.637+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:41:33.637+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:41:33.664+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:41:33.663+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:41:33.701+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.114 seconds
[2023-11-16T20:42:03.847+0000] {processor.py:153} INFO - Started process (PID=25167) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:42:03.848+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:42:03.849+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:42:03.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:42:03.863+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:42:03.877+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:42:03.877+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:42:03.892+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:42:03.892+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:42:03.934+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.089 seconds
[2023-11-16T20:42:34.048+0000] {processor.py:153} INFO - Started process (PID=26947) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:42:34.050+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:42:34.051+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:42:34.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:42:34.088+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:42:34.135+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:42:34.135+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:42:34.190+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:42:34.190+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:42:34.241+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.196 seconds
[2023-11-16T20:43:04.322+0000] {processor.py:153} INFO - Started process (PID=27134) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:43:04.323+0000] {processor.py:743} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2023-11-16T20:43:04.324+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:43:04.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:43:04.336+0000] {processor.py:753} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2023-11-16T20:43:04.357+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:43:04.357+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-11-16T20:43:04.374+0000] {logging_mixin.py:137} INFO - [2023-11-16T20:43:04.373+0000] {dag.py:3437} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2023-11-16T20:43:04.415+0000] {processor.py:175} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.096 seconds
